build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

checks:
    php: true
tools:
    php_code_coverage:
        enabled: true
    external_code_coverage:
        timeout: 600
    php_code_sniffer:
        config:
            standard: PSR12
